services:
  heartify-dl-postgres:
    image: postgres:15-alpine
    container_name: heartify-dl-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-heartify_dl_db}
      POSTGRES_USER: ${POSTGRES_USER:-heartify}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-heartify}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: